rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    #url(r'^logout/$', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from rango.regbackend import MyRegistrationView


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Category model
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


# Page model
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Pages'

    def __str__(self):
        return self.title


# User profile
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User
from registration.forms import RegistrationForm, RegistrationFormTermsOfService, RegistrationFormUniqueEmail

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = self.cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

'''
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')
'''


class UserRegistrationForm(RegistrationFormTermsOfService, RegistrationFormUniqueEmail):
    website = forms.URLField(max_length=200, required=True)
    picture = forms.ImageField(required=True)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# import the Category model
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm, PageForm #UserForm, UserProfileForm
from datetime import datetime


# Create your views here.
def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context_dict)
    return response
    # return HttpResponse("Rango says hey there partner! <br/> <a href='/rango/about/'> About </a>")


def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    print(request.method)
    print(request.user)
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context_dict)
    # return HttpResponse("Rango says here is the about page! <br/> <a href='/rango/'> Index </a>")


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)  # direct user to index page
        else:
            print(form.errors)
    # handle bad forms
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)
    context_dict = {'form': form, 'category': category, }
    return render(request, 'rango/add_page.html', context_dict)

'''
def register(request):
    # True when registration succeeds
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            # remember commit=False
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,
                  'rango/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

'''

'''
# User login
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        # if user exists
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details: {0}, {1}".format(username, password))
            # return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html', {})
'''

# Restriction
def some_view(request):
    if not request.user.is_authenticated():
        return HttpResponse("You are logged in.")
    else:
        return HttpResponse("You are not logged in.")


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})

'''
# Log out
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
'''

# Helper function
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Visitor cookie handler
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        #visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>About Rango</h1>
    <p>This tutorial has been put together by Yuki.</p>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" /><br/>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of cat"/>
    {% if visits %}
        <p> You visited Rango visits: {{ visits }} times!</p>
    {% else %}
        <p> No cookies found QAQ </p>>
    {% endif %}
{% endblock %}

<!--- Code Pre C8>
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<div>
    <p>This tutorial has been put together by Yuki.</p>
</div>

<div>
    <a href="/rango/">Back</a><br/>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango"/>

</div>

<div>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of cat"/>

</div>
</body>
</html>
-->

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category"/>
    </form>
{% endblock %}

<!--- Code Pre C8>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango</title>
</head>
<body>
<h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category"/>
    </form>
</div>

<div>
    <a href="/rango/">Back</a><br/>
</div>
</body>
</html>
-->

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Page
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>Add a page to {{ category.name }}</h1>
        <form id="page_form", method="post", action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Page"/>
        </form>
    {% else %}
        <strong>A category by this name does not exist.</strong>
    {% endif %}
{% endblock %}


<!--- Code Pre C8>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango</title>
</head>
<body>
<div>
    {% if category %}
        <h1>Add a page to {{ category.name }}</h1>
        <form id="page_form", method="post", action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Page"/>
        </form>
    {% else %}
        <strong>A category by this name does not exist.</strong>
    {% endif %}
</div>
<div>
    <a href="/rango/category/{{ category.slug }}/"> Back to {{ category.name }}</a><br/>
    <a href="/rango/"> Back </a>
</div>

</body>
</html>
-->

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block body_block %}
            This is body_block's default content.
        {% endblock %}
    </div>
    <hr/>
    <div>
        <ul>
            {% if user.is_authenticated %}
                <li> <a href="{% url 'rango:restricted' %}"> Restricted Page </a> </li>
                <li> <a href="{% url 'auth_logout' %}?next=/rango/"> Logout </a> </li>
                <li> <a href="{% url 'rango:add_category' %}"> Add a New Category </a> </li>
            {% else %}
                <li> <a href="{% url 'auth_login' %}"> Login </a> </li>
                <li> <a href="{% url 'registration_register' %}"> Sign Up </a> </li>
            {% endif %}

            <li> <a href="{% url 'rango:about' %}"> About </a> </li>
            <li> <a href="{% url 'rango:index' %}"> Index </a> </li>


        </ul>
    </div>

    <div>
        {% block sidebar_block %}
            {% get_category_list category%}
        {% endblock %}
    </div>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            {% if user.is_authenticated %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <ul>
                    {% for page in pages %}
                        <li>{{ page.title }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% else %}
            <strong> No pages currently in category. </strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}"> Add a Page</a>
        {% endif %}
    {% else %}
        The specified page does not exist!
    {% endif %}
{% endblock %}



<!--- Code Pre C8>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango</title>
</head>
<body>
<div>
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong> No pages currently in category. </strong>
        {% endif %}
    {% else %}
        The specified page does not exist!
    {% endif %}
</div>
<div>
    <a href="/rango/category/{{ category.slug }}/add_page/">Add Page</a><br/>
</div>

<div>
    <a href="/rango/"> Back </a>
</div>
</body>
</html>
-->

templates/rango/cats.html
<!DOCTYPE html>
<html lang="en">
     <ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cats %}
            <li>
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
            </li>
            {% else %}
                <li> <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
    </ul>
</html>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
    <h1>Rango says... </h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}
        {% else %}
            <p>hey there partner!</p>
        {% endif %}
    </div>

    <div>
        <h2> Most Liked Categories </h2>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li><a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }} </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

    <div>
        <h2> Most Viewed Pages</h2>
        {% if pages %}
            {% if user.is_authenticated %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}"> {{ page.title }} </a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <ul>
                    {% for page in pages %}
                        <li>{{ page.title }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
    </div>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango"/>
    {% if visits %}
        <p> You visited Rango visits: {{ visits }} times!</p>
    {% else %}
        <p> No cookies found QAQ </p>>
    {% endif %}
{% endblock %}

<!-- Code Pre C8>
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango</title>
</head>

<body>
<h1>Rango says... </h1>
<div>
    hey there partner!
</div>

<div>
<h2> Most Liked Categories </h2>
{% if categories %}
    <ul>
        {% for category in categories %}
            <li><a href="/rango/category/{{ category.slug }}"> {{ category.name }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <strong>There are no categories present.</strong>
{% endif %}
</div>

<div>
<h2> Most Viewed Pages</h2>
{% if pages %}
    <ul>
        {% for page in pages %}
            <li><a href="{{ page.url }}"> {{ page.title }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <strong>There are no pages present.</strong>
{% endif %}
</div>

<div>
    <a href="/rango/add_category/">Add a New Category</a><br/>
</div>

<div>
    <a href="{% url 'rango:about' %}">About Rango</a><br/>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango"/>

</div>

</body>
</html>
-->

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50"/> <br/>
        Password: <input type="password" name="password" value="" size="50"/> <br/>
        <input type="submit" value="submit"/>
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong><br/>
        <a href="{% url 'rango:index' %}">Return to home page.</a><br/>
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Display each form -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <!-- Button for submission-->
        <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock %}

{% block body_block %}
    <p>Since you are logged in, you can see this text!</p>
{% endblock %}